### ISSUE TITLE
400 Invalid request

### ISSUE THREAD

**Issue by MichaelAronsen** [yonjah/piwigo-privacy#1]
All requests for images result in 400 invalid request after following the instructions to set this up, nginx error log below, any ideas?

2016/08/04 14:33:09 [error] 20337#20337: *17 FastCGI sent in stderr: "PHP message: 400 Invalid request - path 192.168.1.152" while reading response header from upstream, client: 192.168.1.152, server: _, request: "GET /_data/i/upload/2016/08/04/20160804141627-f473d164-th.jpg HTTP/1.1", subrequest: "/auth.php", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "192.168.1.160", referrer: "http://192.168.1.160/index.php?/category/3"
2016/08/04 14:33:09 [error] 20337#20337: *17 auth request unexpected status: 400 while sending to client, client: 192.168.1.152, server: _, request: "GET /_data/i/upload/2016/08/04/20160804141627-f473d164-th.jpg HTTP/1.1", host: "192.168.1.160", referrer: "http://192.168.1.160/index.php?/category/3"
2016/08/04 14:33:09 [error] 20337#20337: *16 FastCGI sent in stderr: "PHP message: 400 Invalid request - path 192.168.1.152" while reading response header from upstream, client: 192.168.1.152, server: _, request: "GET /_data/i/upload/2016/08/04/20160804141627-f473d164-th.jpg HTTP/1.1", subrequest: "/auth.php", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "192.168.1.160", referrer: "http://192.168.1.160/index.php?/category/3"
2016/08/04 14:33:09 [error] 20337#20337: *16 auth request unexpected status: 400 while sending to client, client: 192.168.1.152, server: _, request: "GET /_data/i/upload/2016/08/04/20160804141627-f473d164-th.jpg HTTP/1.1", host: "192.168.1.160", referrer: "http://192.168.1.160/index.php?/category/3"

**Comment by yonjah** [comment]
I'll try to see if I can reproduce this over the weekend.

Which NGINX and Piwigo version are you using ?

**Comment by yonjah** [comment]
I looked at the links in the error msg and can't really see any issue with them.
I did made a small change to the auth.php script so try to use the updated version, but I don't think it should have any effect on your issue.

**Comment by MichaelAronsen** [comment]
I changed:
return isset($match[1]) ? $match[1] : null;
To:
return isset($match[0]) ? $match[0] : null;

And it seems to work fine now...

Versions:
ii  nginx                            1.10.0-0ubuntu0.16.04.2             all 
Piwigo is 2.8.0

**Comment by yonjah** [comment]
Oh that's weird.
The first array item should contain the whole match and not only the image part
So unless you also changed the regex to only match the image part and ignore the date prefix I can't see why that would work.

BTW you might wanna upgrade to piwigo 2.8.2  cause 2.8.0 had some issues with the randomness of the e-mail tokens

**Comment by MichaelAronsen** [comment]
I am actually on 2.8.2 now that I look closer..

I did some debugging, match[1] was empty, match[1] contained path to the image, minus the file extension.. did not think it would work, but it seems to work quite well..

**Comment by yonjah** [comment]
A bit weird but I'm glade you got it to work :-)

**Comment by yonjah** [comment]
@MichaelAronsen I rewrote most of the logic of this plugin and fixed some issues.
It is not yet on the master branch but if you want you can check it here -
https://github.com/yonjah/piwigo_privacy/tree/plugin-alpha
