### ISSUE TITLE
How is this different to built-in privacy?

### ISSUE THREAD

**Issue by barbalion** [yonjah/piwigo-privacy#10]
It's unclear how this is different to built-in privacy?
Enabling 
```
    $conf['derivative_url_style']=2;
    $conf['original_url_protection'] = 'all';
```
in config does the same...

**Comment by yonjah** [comment]
`original_url_protection` only makes the image url hard to guess it does not actually check if user has permission to access the image or not.

**Comment by alexmogavero** [comment]
For the original file the authentication of the built-in seems to work. 
The link to my picture is `photos/action.php?id=15297&part=e` and when accessed in incognito mode it gives me `Access denied` error.
For derivative images nothing works instead, I still get simple easy to guess links, so I might be doing something wrong.
