### ISSUE TITLE
piwigo_privacy appears to block exif metadata display on the picture page

### ISSUE THREAD

**Issue by philtuckey** [yonjah/piwigo-privacy#17]
Hi @yonjah 
piwigo_privacy appears to block exif metadata display on the picture page.
To reproduce:
- de-activate piwigo_privacy
- click on an image in an album, i.e. go to the "picture" page for an image which contains exif data (the image itself does not appear on the page because piwigo_privacy is deactivated)
- click on the "show file metadata" button (it's a toggle): the displayed information changes each time the button is clicked, an "EXIF Metadata" section appears and disappears.
- activate piwigo_privacy
- go to the "picture" page for an image which contains exif data
- now clicking on the "show file metadata" button has no effect on the information which is displayed, the "EXIF Metadata" section never appears.
I haven't tried to debug this yet. It took me some time to figure out piwigo_privacy was causing it.
I would appreciate knowing if you see this behaviour or if it's just my setup.

**Comment by yonjah** [comment]
I think I can reproduce this issue (never really used the metadata feature).

I'll see if I can find the cause for this (I assume I'll need to implemented the required logic to pass and display the metadata request as I was not aware of it)

**Comment by dgrammlich** [comment]
I had a further look at this issue [in the _exiftool_gps_ extension](https://github.com/ramack/exiftool_gps/issues/6#issuecomment-535373520), which relies on a certain filepath. With _piwigo_privacy_ activated the filepath changes and the picture is not found anymore, therefore no metadata is shown.

I'm still unsure how to handle this but would be happy to provide some code here or at _exiftool_gps_. :slightly_smiling_face:

**Comment by yonjah** [comment]
@dgrammlich  I haven't really used any of the metadata feature or the gps extension.

I should have some spare time this week so I'll try to check this issue. I'll let you know if I need some more info.

Feel free to ping me in a few days

**Comment by yonjah** [comment]
@dgrammlich  I think this should be solved now.
I haven't checked with the gps extension, but the underlying bug affecting the file path should be fixed.

**Comment by dgrammlich** [comment]
@yonjah This works perfectly combined with the _exiftool_gps_ extension, thanks a lot! :blush:

**Comment by philtuckey** [comment]
I confirm this solves my original issue.

Thanks very much!
