### ISSUE TITLE
becoming a contributor

### ISSUE THREAD

**Issue by extorn** [yonjah/piwigo-privacy#29]
Hi @yonjah,

Firstly, this isn't an issue. I'm just not sure how to get this kind of message to you.

Would you be interested in adding me as a developer on this repository so as I can help maintain this plugin?

The recent changes I've pushed are, I think, needed, and the plugin is working fine for me under Piwigo 11.
I don't wish to fork and then release a fork on the Piwigo extensions site, but the Piwigo users could benefit from this plugin still with version 11+. Or, do you know something that I don't?

Many thanks

Gareth

**Comment by yonjah** [comment]
Hi @extorn, Thank you so much for your contributions.
I had been pretty busy and missed some of the github e-mails, but I'd look into reviewing and merging them as fast as I can.

As I will anyway need to review changes before they are merged I don't think changing any of the github roles will matter much, but feel free to send an MR to add attribution to the readme if you like.

I've been using the plugin with Piwigo latest version with no issues but my Piwigo use is very basic so there might be some edge cases that needs to be tweaked.
