### ISSUE TITLE
Installation instructions could be better.

### ISSUE THREAD

**Issue by extorn** [yonjah/piwigo-privacy#6]
Hi,

Firstly, this is not an issue with your plugin as such - I'm sure its great. I'm struggling to get it working in my install though, so perhaps the installation instructions could be even more helpful :-).

I installed the plugin using the plugin manager on piwigo (latest version). It created a plugin folder with a .git suffix. Once I renamed the folder to remove the suffix, the plugin was visible in piwigo.
I can't get the privacy plugin working using the nginx configuration file though. Admittedly I'm serving piwigo from a subfolder in the domain, but I think I've adapted the configuration correctly yet no images are served. I just see a blank for each image.
The error log shows lots of errors similar to this:

2017/04/29 09:40:24 [error] 29801#29801: *1 open() "/var/www/piwigo/107/_data/i/upload/2017/04/28/20170428215659-daa02cd9-th.jpg" failed (2: No such file or directory), client: &lt;internal IP>, server: &lt;internal IP>, request: "GET /piwigo/107/_data/i/upload/2017/04/28/20170428215659-daa02cd9-th.jpg HTTP/2.0", host: "&lt;server hostname>", referrer: "https://&lt;server hostname>/piwigo/"

I'd be grateful if you could adapt the installation instructions to assist.

**Comment by yonjah** [comment]
Thanks for that.
Apparently there was an issue with the way i setup the extension to be fetched fromgithub.
Installation should work with no issues now.

As for your nginx config the config provided is only supposed to be used as a guideline. you need to make the necessary adaptations to make it work with your specific installation.
It is hard to debug this sort of stuff without knowing your nginx version and the exact config your using.
But from the error it doesn't seem like you use the plugin at all (the link to the image is not correct and does not go through get.php) 
did you change piwigo config according to the readme ? 
also is `/var/www/piwigo` your correct piwigo path ?

**Comment by extorn** [comment]
Thanks for getting back to me on this. Glad I could help r.e. the 
install. I was thinking along the same lines - its like your plugin just 
isn't being used. But I'm pretty sure the config below is set so as it 
should be.

The /var/www/piwigo is definitely correct, with the root being /var/www.

Nginx is version 1.13.0

My nginx site config file extract inline below:

I've taken out IP address and hostname information, but the rest is as is.

I'm new to nginx, so it could well be I've made a glaring mistake in 
what's below!


server {
     server_name <internal IP address> <external host name>;
     listen 443 ssl http2;
     root /var/www;

     ssl on;
     ssl_certificate /etc/ssl/fullchain.pem;
     ssl_certificate_key /etc/ssl/keys/key.pem;
     ssl_session_timeout 5m;
     ssl_ciphers               'AES128+EECDH:AES128+EDH:!aNULL';
     ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;
     ssl_prefer_server_ciphers on;

     add_header Strict-Transport-Security "max-age=15552000; 
includeSubDomains; preload";
     add_header X-Content-Type-Options nosniff;
     add_header X-Frame-Options "SAMEORIGIN";
     add_header X-XSS-Protection "1; mode=block";
     add_header X-Robots-Tag none;
     add_header X-Download-Options noopen;
     add_header X-Permitted-Cross-Domain-Policies none;

     # cache_purge (with $http_cookies we have unique keys for the user)
     fastcgi_cache_key $http_cookie$request_method$host$request_uri;
     fastcgi_cache_use_stale error timeout invalid_header http_500;
     fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

     access_log  /var/log/nginx/access.log;
     error_log   /var/log/nginx/error.log;

     location ^~ / {
        rewrite / /piwigo last;
     }

    location @piwigo_rewrites {
        rewrite ^/piwigo/picture((/|$).*)$ /picture.php$1 last;
        rewrite ^/piwigo/index((/|$).*)$ /index.php$1 last;
        rewrite ^/piwigo/i((/|$).*)$ /i.php$1 last;
        # for piwigo-openstreetmap
        rewrite ^/piwigo/osmmap((/|$).*)$ /osmmap.php$1 last;
     }

    location /piwigo {
       index index.php;
       try_files $uri $uri/ @piwigo_rewrites;
#       try_files $uri $uri/ =404;
#      auth_basic "Restricted";
#      auth_basic_user_file /var/www/secure-content/.htpasswd;

     location ~* /piwigo/.*\.(?:ico|css|js|jpe?g|png|gif)$ {
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, 
proxy-revalidate";
     }

     location = /piwigo/favicon.ico {
        allow all;
        access_log off;
        log_not_found off;
     }

     location = /piwigo/robots.txt {
        allow all;
        access_log off;
        log_not_found off;
     }

     location ~ \.inc\.php$ {
        deny all;
     }

     location ~ 
^/piwigo/(include|install|local|tools|admin/include|admin/themes|plugins|upload|themes|galleries|_data|doc|language|template-extension)/.*\.php$ 
{
                 deny all;
}

     location ~ /piwigo/\. {
         access_log off;
         log_not_found off;
         deny all;
     }

   location ~ ^/piwigo/(?<script_name>.+?\.php)(?<path_info>/.*)?$ {
         include fastcgi_params;
         fastcgi_split_path_info ^(.+\.php)(/.+)$;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         fastcgi_param PATH_INFO $fastcgi_path_info;
         fastcgi_param HTTPS on;
         #Avoid sending the security headers twice
         fastcgi_param modHeadersAvailable true;
         fastcgi_param front_controller_active true;
         fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
         fastcgi_intercept_errors on;
         fastcgi_request_buffering off;

     }

    location = /piwigo/piwigo_privacy/get.php {
         try_files $uri =404;
         fastcgi_index index.php;
         include fastcgi_params;
         fastcgi_split_path_info ^(.+\.php)(/.+)$;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         fastcgi_param PATH_INFO $fastcgi_path_info;
         fastcgi_param HTTPS on;
         #Avoid sending the security headers twice
         fastcgi_param modHeadersAvailable true;
         fastcgi_param front_controller_active true;
         fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
         fastcgi_intercept_errors on;
         fastcgi_request_buffering off;

     }



     location ~ ^/piwigo/\d+/ {
                 set $script '/piwigo/plugins/piwigo_privacy/get.php';
                 fastcgi_pass unix:/run/php-fpm/www.sock;
                 fastcgi_index  get.php;
                 fastcgi_param  SCRIPT_FILENAME $document_root$script;
                 fastcgi_param  SCRIPT_NAME      $script;
                 include fastcgi_params;
     }

    ### Prevent hotlinks - this section needs to be _after_ the php 
handler above
     #
     # When uploading images via ws.php (e.g. from Lightroom), the are 
requests from Piwigo
     # itself to /i/upload using the servers own IP and "Piwigo" user 
agent. We need to allow those
     ###

     # Only the site's own URL is a valid referer.
     # Empty referers and others like google etc are invalid, see Nginx 
docs for more info
     valid_referers <external host name>/piwigo;
     # initialize empty variable
     set $check_referal "";
     # if referer is not our own hostname, set variable's value to "invalid"
     if ($invalid_referer) {
      set $check_referal "invalid";
     }
     # if the user agent is not "Piwigo", append "not_piwigo" to the value
     if ($http_user_agent !~ "Piwigo") {
      set $check_referal "${check_referal}+not_piwigo";
     }
     # Now, for all images, test if referer is invalid and user agent is 
not piwigo
     # If so, block the request
     location ~* /piwigo/.*\.(gif|png|jpe?g)$ {
        if ($check_referal = "invalid+not_piwigo") {
           return 403;
        }
        try_files $uri $uri/ @piwigo_rewrites;
     }
}

**Comment by yonjah** [comment]
Did  you activate the plugin ?
Did you set the config `$conf['derivative_url_style']=1;`
What is the actual image URL piwigo UI gets? 
If it's not going through get.php you did not properly configured the plugin

You did not set any internal redirect rules so i assume you are not using the accel redirect config.
If you do want to use accel redirect you also need to include the internal routes form the example nginx config

**Comment by extorn** [comment]
Yes, the plugin is active.
I set the config as you instruct.
I tried "advanced mode" and "naiive mode" (by adding in the extra routes you describe).
I've got it working with the following configuration and "naiive mode". Advanced mode fails to work - all images return a 404 error (n.b. I didn't alter this config, just enabled the extra flag in the piwigo config file (piwigo/include/config_default.inc.php

server {
    listen 80;
    #server_name _;
    server_name <external hostname>;
    return 301 https://$server_name$request_uri;
}
server {
    server_name <external hostname>;
    listen 443 ssl http2;
    root /var/www/secure-content;

    ssl on;
    ssl_certificate /etc/ssl/fullchain.pem;
    ssl_certificate_key /etc/ssl/key.pem;
    ssl_session_timeout 5m;
    ssl_ciphers               'AES128+EECDH:AES128+EDH:!aNULL';
    ssl_protocols              TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=15552000; includeSubDomains; preload";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;

    # cache_purge (with $http_cookies we have unique keys for the user)
    fastcgi_cache_key $http_cookie$request_method$host$request_uri;
    fastcgi_cache_use_stale error timeout invalid_header http_500;
    fastcgi_ignore_headers Cache-Control Expires Set-Cookie;

    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    location ^~ / {
       rewrite / /piwigo last;
    }

   location @piwigo_rewrites {
       rewrite ^/piwigo/picture((/|$).*)$ /picture.php$1 last;
       rewrite ^/piwigo/index((/|$).*)$ /index.php$1 last;
       rewrite ^/piwigo/i((/|$).*)$ /i.php$1 last;
       # for piwigo-openstreetmap
       rewrite ^/piwigo/osmmap((/|$).*)$ /osmmap.php$1 last;
    }

location /piwigo {
      index index.php;
      try_files $uri $uri/ @piwigo_rewrites;

    location ~* /piwigo/.*\.(?:ico|css|js|jpe?g|png|gif)$ {
       expires max;
       add_header Pragma public;
       add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    location = /piwigo/favicon.ico {
       allow all;
       access_log off;
       log_not_found off;
    }

    location = /piwigo/robots.txt {
       allow all;
       access_log off;
       log_not_found off;
    }
    
    #### Extra Security blocks not necessary for the plugin, just some added security ####
    location ~ \.inc\.php$ {
       deny all;
    }


    location ~  ^/piwigo/(include|install|local|tools|admin/include|admin/themes|plugins|upload|themes|galleries|_data|doc|language|template-extension)/.*\.php$ {
		deny all;
    }

    location ~ /piwigo/\. {
        access_log off;
        log_not_found off;
        deny all;
    }
    #### End of extra security block ####


    location ~ ^/piwigo/(?<script_name>.+?\.php)(?<path_info>/.*)?$ {
#    location ~ \.php$ {
#        try_files  $uri =404;
#        fastcgi_index  index.php;
#        fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        #Avoid sending the security headers twice
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    location ~ ^/piwigo/\d+/ {
        set $script '/piwigo/plugins/piwigo_privacy/get.php';
        fastcgi_index  get.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$script;
        fastcgi_param  SCRIPT_NAME      $script;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        #Avoid sending the security headers twice
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    location = /piwigo/plugins/piwigo_privacy/get.php {
        try_files  $uri =404;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_NAME  $fastcgi_script_name;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        #Avoid sending the security headers twice
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }


    location = /piwigo/i.php {
        deny all;
    }

    location /piwigo/upload {
        internal;
    }

    location /piwigo/galleries {
        internal;
    }

    location /piwigo/_data {
        internal;
    }

    location /piwigo/_data/combined {
        try_files $uri $uri/ =404;
    }


    ### Prevent hotlinks - this section needs to be _after_ the php handler above
    #
    # When uploading images via ws.php (e.g. from Lightroom), the are requests from Piwigo
    # itself to /i/upload using the servers own IP and "Piwigo" user agent. We need to allow those
    ###

    # Only the site's own URL is a valid referer.
    # Empty referers and others like google etc are invalid, see Nginx docs for more info
    valid_referers https://<external hostname>/piwigo/;
    # initialize empty variable
    set $check_referal "";
    # if referer is not our own hostname, set variable's value to "invalid"
    if ($invalid_referer) {
     set $check_referal "invalid";
    }
    # if the user agent is not "Piwigo", append "not_piwigo" to the value
    if ($http_user_agent !~ "Piwigo") {
     set $check_referal "${check_referal}+not_piwigo";
    }
    # Now, for all images, test if referer is invalid and user agent is not piwigo
    # If so, block the request
    location ~* /piwigo/.*\.(gif|png|jpe?g)$ {
       if ($check_referal = "invalid+not_piwigo") {
          return 403;
       }
       try_files $uri $uri/ @piwigo_rewrites;
    }
} #end piwigo location block

    location ~ /\.ht {
        deny all;
    }

}

**Comment by extorn** [comment]
Yes, the plugin is active.
I set the config as you instruct.
I tried "advanced mode" and "naiive mode" (by adding in the extra routes you describe).
I've got it working with the following configuration and "naiive mode". Success!!!! Advanced mode fails to work - all images return a 404 error (n.b. I didn't alter this config, just enabled the extra flag in the piwigo config file (piwigo/include/config_default.inc.php when testing advanced mode. Is there something else I need to do? What are the advantages / disadvantages of advanced mode?

Thanks for your ongoing help.

[nginx-site.txt](https://github.com/yonjah/piwigo_privacy/files/968704/nginx-site.txt)

**Comment by yonjah** [comment]
I think you need to go over you nginx conf and see what you really need there.
Your conf is too messy to understand what's going on and there is too much ambiguity where multiple locations might match a single URL.

I would suggest your start from the most simple nginx.conf with the single most important feature you need and slowly add features one by one considering how they fit the existing rules.

As with this plugin there is almost no advantage for using the `advance` mode over the `naive` mode. but with so much stuff going on your nginx.conf it's hard to know if static files can't be served from a different location so I would suggest you cleaning the conf any way but I'm closing this issue since it is not really a problem with this plugin

**Comment by extorn** [comment]
Understood. Thank you for your comments and your time.
