### ISSUE TITLE
Standard users cannot do all actions - e.g. play videos

### ISSUE THREAD

**Issue by extorn** [yonjah/piwigo-privacy#8]
Because the user variable is not setup, only admin users (because you manually build part of the user array in helper_funcs.inc.php line 201) are able to do certain actions.

line 198 (just before "`if( $is_admin() ) {`" insert line `"global $user;`"
line 201 (`$user['enabled_high']=true` should be deleted - no override just because you're an admin user.

The resultant block looks like this:

`global $user;`
`        if ( is_admin() ) {`
`                $is_admin_download = true;`
`        }`

**Comment by yonjah** [comment]
Thanks.
`$user` was actually defined but there was a missing global declaration in the function that uses it.
This is fixed in v0.1.3
